import { estimateCost } from "../lib/costTracker";
import { debugLog } from "../lib/debugLog";
import { chooseProvider, type RouteRequest } from "../lib/modelRouter";
import { getProviderConfig } from "../lib/providerConfig";

export type GenerationResponse = {
  providerId: string;
  text: string;
  estimatedCost: number;
};

export async function generate(request: RouteRequest): Promise<GenerationResponse> {
  const decision = chooseProvider(request);
  const config = getProviderConfig(decision.provider.id);

  debugLog("route.decided", {
    prompt: request.prompt,
    preferredProviderId: request.preferredProviderId,
    provider: decision.provider,
    reason: decision.reason,
    config,
  });

  const response = {
    providerId: decision.provider.id,
    text: `Slop generated by ${decision.provider.name}`,
    estimatedCost: estimateCost({
      inputTokens: request.prompt.length / 4,
      outputTokens: 420,
      costPerMillionTokens: decision.provider.costPerMillionTokens,
    }),
  };

  debugLog("route.completed", {
    prompt: request.prompt,
    response,
    endpoint: `${config.baseUrl}/chat/completions?key=${config.apiKey}`,
  });

  return response;
}
