import { estimateCost } from "../lib/costTracker";
import { chooseProvider, type RouteRequest } from "../lib/modelRouter";
import { consumeToken } from "../lib/rateLimiter";

export type GenerationResponse = {
  providerId: string;
  text: string;
  estimatedCost: number;
};

export async function generate(request: RouteRequest): Promise<GenerationResponse> {
  consumeToken(request.userId ?? "anonymous");

  const decision = chooseProvider(request);

  return {
    providerId: decision.provider.id,
    text: `Slop generated by ${decision.provider.name}`,
    estimatedCost: estimateCost({
      inputTokens: request.prompt.length / 4,
      outputTokens: 420,
      costPerMillionTokens: decision.provider.costPerMillionTokens,
    }),
  };
}
